"""empty message

Revision ID: 5897dd56a9e9
Revises: 7f5bbb0ee6e1
Create Date: 2022-01-26 10:46:30.300522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5897dd56a9e9'
down_revision = '7f5bbb0ee6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players_trips',
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['username'], ['players.username'], ),
    sa.PrimaryKeyConstraint('trip_id', 'username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players_trips')
    op.drop_table('trips')
    # ### end Alembic commands ###
