"""empty message

Revision ID: 6e83571d0543
Revises: 15fbe4ce36a9
Create Date: 2022-02-08 15:19:07.967374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e83571d0543'
down_revision = '15fbe4ce36a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_players_trips', sa.Column('trip_owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_players_trips', 'trip_owner')
    # ### end Alembic commands ###
