"""empty message

Revision ID: 77276bd0a416
Revises: 6e83571d0543
Create Date: 2022-02-08 15:30:07.011420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77276bd0a416'
down_revision = '6e83571d0543'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_players_trips', sa.Column('trip_owner_id', sa.Integer(), nullable=True))
    op.drop_column('pending_players_trips', 'trip_owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_players_trips', sa.Column('trip_owner', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pending_players_trips', 'trip_owner_id')
    # ### end Alembic commands ###
