"""empty message

Revision ID: 7a92003edd26
Revises: 0c16b45274bc
Create Date: 2022-01-31 13:31:16.127694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a92003edd26'
down_revision = '0c16b45274bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('visible_on_leaderboard', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'visible_on_leaderboard')
    # ### end Alembic commands ###
