"""empty message

Revision ID: 7ac472fab7c6
Revises: d3557cf0746e
Create Date: 2022-01-26 09:51:08.674343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ac472fab7c6'
down_revision = 'd3557cf0746e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'test_thing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('test_thing', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
